name: jobs-app
recipe: laravel
config:
  php: '8.3'
  webroot: public
  via: nginx
  database: mysql:8.0
services:
  node:
    type: node:20
    ssl: 3000
    healthcheck: false
  appserver:
    type: php:8.3
tooling:
  install:
    cmd:
      - appserver: composer install --no-cache
      - appserver: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - appserver: php artisan key:generate
      - appserver: php artisan migrate --seed
      - node: npm install
      - appserver: php artisan storage:link
  setup:
    cmd:
      - appserver: composer install --no-cache
      - appserver: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - appserver: php artisan key:generate
      - appserver: php artisan migrate --seed
      - node: npm install
      - appserver: php artisan storage:link
  tinker:
    service: appserver
    cmd: php artisan tinker
  migrate:
    service: appserver
    cmd: php artisan migrate
  rollback:
    service: appserver
    cmd: php artisan migrate:rollback --step=1

